spring:
  config:
    activate:
      on-profile: sub

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_MASTER_USER_NAME}
    password: ${AWS_MASTER_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082